export const notes = [
  { id: "tokens", category: "foundations", number: "01", tag: "FOUNDATIONS", title: "Tokens are the interface", description: "What a model actually sees, why text becomes integers, and where the seams show.", meta: "12 min read", question: "Why can't the model see words?" },
  { id: "embeddings", category: "foundations", number: "02", tag: "FOUNDATIONS", title: "Meaning in a vector", description: "A geometric intuition for embeddings, similarity, and the strange power of coordinates.", meta: "18 min read", question: "How does a model store meaning?" },
  { id: "attention", category: "foundations", number: "03", tag: "FOUNDATIONS", title: "Attention is a lookup", description: "Build the core operation by hand. Queries, keys, values—and why context has a cost.", meta: "24 min read", question: "How does context enter the computation?" },
  { id: "training", category: "foundations", number: "04", tag: "FOUNDATIONS", title: "Loss is a compass", description: "The training loop as a measurement instrument, not a ritual. Follow the gradient.", meta: "21 min read", question: "What does 'learning' mean here?" },
  { id: "transformers", category: "systems", number: "05", tag: "SYSTEMS", title: "The transformer stack", description: "The smallest complete map of the architecture: blocks, residuals, norms, and logits.", meta: "31 min read", question: "What is the machine made of?" },
  { id: "scaling", category: "systems", number: "06", tag: "SYSTEMS", title: "Scale changes the game", description: "Parameters, data, compute, and the empirical laws that make bigger surprisingly useful.", meta: "16 min read", question: "Why does scale work?" },
  { id: "inference", category: "systems", number: "07", tag: "SYSTEMS", title: "One token at a time", description: "Sampling, temperature, KV caches, and the time-sensitive path from prompt to response.", meta: "19 min read", question: "What happens at inference?" },
  { id: "evaluation", category: "systems", number: "08", tag: "SYSTEMS", title: "Measure the thing", description: "A practical evaluation loop for when benchmark scores are not enough—or even relevant.", meta: "22 min read", question: "How do I know if it works?" },
  { id: "rag", category: "shipping", number: "09", tag: "SHIPPING", title: "Give it a library", description: "Retrieval augmented generation without the hand-waving: chunk, search, cite, inspect.", meta: "27 min read", question: "How can a model use my data?" },
  { id: "finetuning", category: "shipping", number: "10", tag: "SHIPPING", title: "Teach, don't just prompt", description: "When to use fine-tuning, what the dataset is really doing, and how to avoid cargo culting.", meta: "25 min read", question: "When should I change the weights?" },
  { id: "agents", category: "shipping", number: "11", tag: "SHIPPING", title: "Tools make a system", description: "The useful unit is often a model surrounded by tools, state, checks, and a clear stop condition.", meta: "23 min read", question: "How does a model take action?" },
  { id: "production", category: "shipping", number: "12", tag: "SHIPPING", title: "Ship the boring parts", description: "Latency, cost, observability, fallbacks, and the path from demo to something people trust.", meta: "29 min read", question: "What survives contact with users?" },
  { id: "knowledge-graphs", category: "shipping", number: "13", tag: "SHIPPING", title: "A graph is a hypothesis", description: "Turn a document into an inspectable representation, review it, and improve the next pass without creating a second source of truth.", meta: "20 min read", question: "How does a document become a representation you can improve?" }
];

export const noteDetails = {
  tokens: ["A language model never receives words. It receives a sequence of token IDs produced by a tokenizer. That boundary explains spelling weirdness, context limits, cost, and why changing one character can change the whole computation.", "Write a byte-pair tokenizer for a small text file. Print token IDs, decoded text, and compression ratio for five surprising strings.", "Compare how your tokenizer splits a name, an emoji, code, and a sentence in another language."],
  embeddings: ["An embedding is a learned coordinate system. Similar uses tend to land near one another, but the dimensions are not a hand-labeled dictionary—they are shaped by the task and the data.", "Load a small embedding model and plot 30 words with PCA. Label clusters, then inspect the nearest neighbors of an ambiguous word.", "Find one useful neighborhood and one misleading one. Ask what the corpus taught the geometry."],
  attention: ["Attention lets every position make a weighted lookup over other positions. Queries ask what is needed, keys advertise what is available, and values carry the information back.", "Implement scaled dot-product attention in a few lines of array code. Print the attention matrix for a sentence and explain one row.", "Mask future positions and watch the matrix become causal—the small detail that turns a lookup into language modeling."],
  training: ["Loss compresses a prediction error into a signal that can move parameters. It is useful because it is differentiable, not because it perfectly captures usefulness.", "Run `node experiments/tiny-training.mjs`, read the character-level bigram model, then change its steps and learning rate before adding architecture.", "Keep the loss falling while making the output worse. That tension is the beginning of evaluation."],
  transformers: ["A transformer repeats a simple block: mix information across positions with attention, transform each position with an MLP, and preserve a clean path with residual connections.", "Implement a character-level transformer with one block. Keep it small enough to read every tensor shape in a debugger.", "Remove one component at a time. Record which failure is graceful, catastrophic, or merely slower."],
  scaling: ["More parameters alone are not a strategy. Useful scaling balances model capacity, data, and compute so the model keeps finding structure rather than memorizing noise.", "Train three tiny models under a fixed compute budget. Log parameter count, tokens seen, wall time, and validation loss.", "Use the measurements to predict which model should win before checking the result."],
  inference: ["Generation is a loop: run the model, turn logits into a distribution, choose one token, append it, and repeat. The cache keeps old key/value computations from being repeated.", "Write a sampler with greedy, temperature, and top-k modes. Time it with and without a simple key/value cache.", "Generate the same prompt at three temperatures and describe the change without using the word “creative.”"],
  evaluation: ["Evaluation is a decision instrument. Define the user task, create representative examples, record acceptable failures, and measure changes with a repeatable harness.", "Create a 30-example eval set for one narrow task. Include adversarial and ambiguous cases, a rubric, and a baseline.", "Have two people score the same outputs. Investigate disagreement before adding more examples."],
  rag: ["Retrieval gives a model relevant context at request time instead of asking its weights to contain every fact. The quality bottleneck is often search and chunking, not the final prompt.", "Index ten documents with simple lexical search. Return the top three chunks with source labels before asking the model to answer.", "Create questions whose answer spans two chunks. See whether your retriever brings both pieces together."],
  finetuning: ["Fine-tuning changes behavior through examples. It fits repeatable format, style, or task behavior—not a magic database update.", "Write 50 high-quality input/output examples for one narrow behavior. Hold out a test set and compare prompt-only versus tuned behavior.", "Remove the weakest quarter of your examples. If performance improves, your dataset was teaching noise."],
  agents: ["An agent is a control loop around a model: decide, call a tool, observe, and decide again. Reliability comes from constrained actions and explicit checks, not a grander persona.", "Give a model exactly two tools and a maximum of five steps. Log every decision, tool input, output, and stop reason.", "Add a dry-run mode. A safe system should be inspectable before it is powerful."],
  production: ["A production system is a set of promises: response time, cost, availability, data handling, and behavior when the model is wrong or unavailable.", "Make a request log with latency, token counts, model version, outcome, and a redacted trace. Add one fallback and one human escape hatch.", "Ask a real person to use the system without your narration. Every question they ask is a missing product surface."],
  "knowledge-graphs": ["A knowledge graph is an inspectable hypothesis about concepts, relations, and evidence—not a magical summary. Human review turns corrections into bounded guidance for the next extraction.", "Take one paragraph and record concepts, relations, evidence, and review status separately. Export the result into Markdown or Obsidian and preserve its graph fingerprint.", "Reject one candidate and accept one missing concept. Re-run the extraction with those compact decisions and compare which claims became easier to inspect."]
};
