import assert from "node:assert/strict";
import fs from "node:fs";

const html = fs.readFileSync(new URL("../index.html", import.meta.url), "utf8");
const manifest = JSON.parse(fs.readFileSync(new URL("../manifest.webmanifest", import.meta.url), "utf8"));
const release = JSON.parse(fs.readFileSync(new URL("../version.json", import.meta.url), "utf8"));
const graphSchema = JSON.parse(fs.readFileSync(new URL("../schema/graph.schema.json", import.meta.url), "utf8"));
const feedbackSchema = JSON.parse(fs.readFileSync(new URL("../schema/feedback.schema.json", import.meta.url), "utf8"));
const backupSchema = JSON.parse(fs.readFileSync(new URL("../schema/backup.schema.json", import.meta.url), "utf8"));
const diffSchema = JSON.parse(fs.readFileSync(new URL("../schema/diff.schema.json", import.meta.url), "utf8"));
const evaluationSchema = JSON.parse(fs.readFileSync(new URL("../schema/evaluation.schema.json", import.meta.url), "utf8"));
const evaluationComparisonSchema = JSON.parse(fs.readFileSync(new URL("../schema/evaluation-comparison.schema.json", import.meta.url), "utf8"));
const healthSchema = JSON.parse(fs.readFileSync(new URL("../schema/health.schema.json", import.meta.url), "utf8"));
const jsonLdSchema = JSON.parse(fs.readFileSync(new URL("../schema/jsonld.schema.json", import.meta.url), "utf8"));
const vaultManifestSchema = JSON.parse(fs.readFileSync(new URL("../schema/vault-manifest.schema.json", import.meta.url), "utf8"));
const requestSchema = JSON.parse(fs.readFileSync(new URL("../schema/extractor-request.schema.json", import.meta.url), "utf8"));
const app = fs.readFileSync(new URL("../app.js", import.meta.url), "utf8");
const jsonLdProjection = fs.readFileSync(new URL("../jsonld-projection.js", import.meta.url), "utf8");
const graphCore = fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8");
const serviceWorker = fs.readFileSync(new URL("../sw.js", import.meta.url), "utf8");
const publicAssets = fs.readFileSync(new URL("../scripts/public-assets.mjs", import.meta.url), "utf8");
const bugTemplate = fs.readFileSync(new URL("../.github/ISSUE_TEMPLATE/bug_report.yml", import.meta.url), "utf8");
const featureTemplate = fs.readFileSync(new URL("../.github/ISSUE_TEMPLATE/feature_request.yml", import.meta.url), "utf8");
const learningNoteTemplate = fs.readFileSync(new URL("../.github/ISSUE_TEMPLATE/learning_note.yml", import.meta.url), "utf8");
const security = fs.readFileSync(new URL("../SECURITY.md", import.meta.url), "utf8");
const conduct = fs.readFileSync(new URL("../CODE_OF_CONDUCT.md", import.meta.url), "utf8");
const notesIndex = fs.readFileSync(new URL("../notes/README.md", import.meta.url), "utf8");
const llms = fs.readFileSync(new URL("../llms.txt", import.meta.url), "utf8");
const robots = fs.readFileSync(new URL("../robots.txt", import.meta.url), "utf8");
const server = fs.readFileSync(new URL("../server.mjs", import.meta.url), "utf8");
const publicOrigin = fs.readFileSync(new URL("../scripts/public-origin.mjs", import.meta.url), "utf8");
const dockerfile = fs.readFileSync(new URL("../Dockerfile", import.meta.url), "utf8");
const dockerignore = fs.readFileSync(new URL("../.dockerignore", import.meta.url), "utf8");
const notesDirectory = new URL("../notes/", import.meta.url);
const dependabot = fs.readFileSync(new URL("../.github/dependabot.yml", import.meta.url), "utf8");
const packageManifest = JSON.parse(fs.readFileSync(new URL("../package.json", import.meta.url), "utf8"));

for (const id of ["workbench", "try-sample", "app-error", "reload-app", "document-file", "document-uri", "ingest-document", "extractor-endpoint", "cancel-extraction", "clear-graph", "undo-graph", "graph-search", "manual-node-label", "add-manual-node", "manual-edge-source", "manual-edge-target", "add-manual-edge", "graph-canvas", "node-list", "relation-list", "inspector-panel", "graph-health", "revision-diff-preview", "download-markdown", "copy-markdown", "download-redacted-markdown", "download-vault", "download-redacted-vault", "download-json", "download-health", "download-redacted", "download-backup", "download-feedback", "download-compact-feedback", "download-diff", "release-version"]) {
  assert(html.includes(`id="${id}"`), `missing required element: ${id}`);
}
assert(html.includes('id="inspector-panel" tabindex="-1" aria-live="polite"') && app.includes('document.querySelector("#inspector-panel").focus()'), "review navigation should move focus to the inspector");
for (const match of html.matchAll(/<label[^>]+for="([^"]+)"/g)) {
  assert(html.includes(`id="${match[1]}"`), `label target is missing: ${match[1]}`);
}
assert(/id="document-file"[^>]*multiple/.test(html), "document input should support batches");
assert(/id="document-title"[^>]*maxlength="200"/.test(html), "document titles should match the request contract bound");
assert(html.includes('id="file-queue"'), "file queue status should be visible");
for (const match of app.matchAll(/<button\b[^>]*>/g)) {
  assert(/\btype="button"/.test(match[0]), `rendered app button should declare type=button: ${match[0]}`);
}
for (const asset of ["./index.html", "./styles.css", "./app.js", "./graph-core.js", "./graph-store.js", "./extractor-adapter.js", "./projection-adapter.js", "./jsonld-projection.js", "./storage-adapter.js", "./evaluation.js", "./manifest.webmanifest", "./icon.svg", "./social-card.svg", "./version.json", "./schema/graph.schema.json", "./schema/feedback.schema.json", "./schema/backup.schema.json", "./schema/diff.schema.json", "./schema/extractor-request.schema.json", "./schema/evaluation.schema.json", "./schema/evaluation-comparison.schema.json", "./schema/health.schema.json", "./schema/jsonld.schema.json"]) {
  assert(serviceWorker.includes(asset), `service worker missing shell asset: ${asset}`);
}
assert.equal(manifest.name, "LLM Field Notes");
assert.equal(release.version, packageManifest.version, "the public release manifest should match package.json");
assert.equal(release.channel, "unreleased", "the current release manifest should declare its release channel");
assert(app.includes("version.json") && app.includes("release-version"), "the public footer should use the release manifest");
assert(html.includes('id="release-version">release metadata unavailable</span>'), "the public footer should use a neutral static release fallback");
assert(app.includes("setNoteMetadata") && app.includes("restorePageMetadata") && app.includes("meta[property=\"og:title\"]"), "note deep links should update and restore share metadata");
assert.equal(manifest.id, "./");
assert.equal(manifest.scope, "./");
assert.equal(manifest.start_url, "./#workbench");
assert.deepEqual(manifest.categories, ["education", "productivity", "developer"]);
assert.equal(manifest.shortcuts.length, 3, "the installable app should expose launcher shortcuts");
assert.equal(manifest.shortcuts[2].url, "./#sample", "the installable app should expose a sample graph shortcut");
assert(publicAssets.includes('"LICENSE"') && html.includes('href="LICENSE" rel="license"'), "the public deployment should expose and semantically link its license");
assert(publicAssets.includes('"llms.txt"') && html.includes('href="llms.txt"'), "the public deployment should expose an LLM-readable project map");
assert(llms.includes("./schema/jsonld.schema.json") && llms.includes("JSON-LD schema"), "the project map should document the JSON-LD contract");
assert(publicAssets.includes('"schema/vault-manifest.schema.json"'), "the vault manifest schema should be publicly deliverable");
const readme = fs.readFileSync(new URL("../README.md", import.meta.url), "utf8");
assert(!readme.includes("Open `index.html` directly") && readme.includes("There are no runtime dependencies."), "onboarding should describe the dependency-free HTTP workflow accurately");
assert(fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("npm run serve"), "onboarding should document the dependency-free local server");
assert.equal(packageManifest.scripts.start, "node server.mjs", "production Node hosts should have a standard start command");
assert.equal(packageManifest.scripts.diff, "node experiments/diff-graphs.mjs", "graph diff should have a documented package command");
assert.equal(packageManifest.scripts["release:check"], "node scripts/check-release.mjs", "release metadata should have an automated consistency command");
assert(fs.existsSync(new URL("../scripts/check-release.mjs", import.meta.url)), "release consistency check should remain deliverable");
assert(fs.readFileSync(new URL("../scripts/build-pages.mjs", import.meta.url), "utf8").includes("PUBLIC_ORIGIN") && fs.readFileSync(new URL("../scripts/build-pages.mjs", import.meta.url), "utf8").includes("buildStaticSitemap"), "Pages builds should support origin-aware crawler discovery");
const pagesBuildWorkflow = fs.readFileSync(new URL("../.github/workflows/pages.yml", import.meta.url), "utf8");
assert(pagesBuildWorkflow.includes("id: pages") && pagesBuildWorkflow.includes("steps.pages.outputs.base_url") && pagesBuildWorkflow.indexOf("id: pages") < pagesBuildWorkflow.indexOf("Build safe Pages bundle"), "Pages deployment should derive crawler URLs before building the static artifact");
assert(fs.readFileSync(new URL("../scripts/check-release.mjs", import.meta.url), "utf8").includes("toISOString().slice(0, 10)") && fs.readFileSync(new URL("../scripts/check-release.mjs", import.meta.url), "utf8").includes("APP_SHELL") && fs.readFileSync(new URL("../scripts/check-release.mjs", import.meta.url), "utf8").includes("PUBLIC_ASSETS") && fs.readFileSync(new URL("../scripts/check-release.mjs", import.meta.url), "utf8").includes("LEARNING_NOTE_ASSETS") && fs.readFileSync(new URL("../scripts/check-release.mjs", import.meta.url), "utf8").includes("metadata.isFile()") && fs.readFileSync(new URL("../scripts/check-release.mjs", import.meta.url), "utf8").includes("workflowDirectory"), "release checks should validate dates, public assets, learning-note parity, and every workflow");
assert(serviceWorker.includes(`const CACHE = "llm-field-notes-v${packageManifest.version}"`), "service worker cache version should track the release version");
assert(serviceWorker.includes("./LICENSE"), "service worker should precache the public license");
assert(serviceWorker.includes("./SECURITY.md"), "service worker should precache public security guidance");
assert(serviceWorker.includes("./social-card.svg"), "service worker should precache the social share card");
assert(serviceWorker.includes("./CODE_OF_CONDUCT.md"), "service worker should precache community guidance");
assert(serviceWorker.includes("./CONTRIBUTING.md"), "service worker should precache the contribution entry point");
assert(serviceWorker.includes("./notes/tokens.md") && serviceWorker.includes("./notes/production.md"), "service worker should precache learning notes");
assert(serviceWorker.includes("cache: \"no-cache\"") && serviceWorker.includes("AbortController") && serviceWorker.includes("NETWORK_TIMEOUT_MS") && serviceWorker.includes("matchShellCache") && serviceWorker.includes("caches.match") && serviceWorker.includes("if (networkResponse) return networkResponse"), "service worker should bound shell revalidation and fall back for offline or transient HTTP failures");
assert(serviceWorker.includes("isShellRequest") && serviceWorker.includes("SHELL_PATHS") && serviceWorker.includes("CACHE_PREFIX") && serviceWorker.includes("startsWith(CACHE_PREFIX)"), "service worker should restrict interception and cache cleanup to this app");
assert(app.includes('register("./sw.js", { updateViaCache: "none" })') && app.includes("registration.update()"), "the app should discover service-worker updates without stale HTTP cache entries");
assert.equal(graphSchema.properties.schema.const, "llm-field-notes/graph@1");
assert.equal(graphSchema.properties.revisions.maxItems, 20, "graph schema should bound retained revisions");
assert.equal(graphSchema.properties.learning.properties.examples.maxItems, 500, "graph schema should bound reusable learning memory");
assert.equal(graphSchema.$defs.node.properties.lastReviewedAt.maxLength, 128, "concept review timestamps should be bounded");
assert.equal(graphSchema.$defs.edge.properties.lastReviewedAt.maxLength, 128, "relation review timestamps should be bounded");
assert.equal(graphSchema.$defs.learningExample.properties.lastReviewedAt.maxLength, 128, "learning review timestamps should be bounded");
assert.equal(feedbackSchema.properties.examples.items.properties.lastReviewedAt.maxLength, 128, "feedback review timestamps should be bounded");
assert.equal(graphSchema.properties.integrity.properties.ambiguousSourceIds.maxItems, 100, "graph schema should bound provenance ambiguity diagnostics");
assert.equal(graphSchema.properties.integrity.properties.ambiguousEdgeIds.maxItems, 100, "graph schema should bound edge identity ambiguity diagnostics");
assert.equal(graphSchema.properties.version.maximum, 9007199254740991, "graph schema should bound versions to safe integers");
assert.equal(vaultManifestSchema.properties.format.const, "llm-field-notes/vault@1", "vault manifests should have a versioned schema contract");
assert.equal(vaultManifestSchema.properties.graphFingerprint.pattern, "^fnv64-[0-9a-f]{16}-[0-9]+$", "vault manifests should bind exports to graph fingerprints");
assert.equal(vaultManifestSchema.properties.graphFingerprint.maxLength, 128, "vault manifest fingerprints should be bounded");
assert.equal(jsonLdSchema.properties.format.const, "llm-field-notes/jsonld@1", "JSON-LD projections should declare a versioned contract");
assert.equal(jsonLdSchema.properties.fingerprint.pattern, "^fnv64-[0-9a-f]{16}-[0-9]+$", "JSON-LD projections should bind to graph fingerprints");
assert.equal(jsonLdSchema.properties["@graph"].items.$ref, "#/$defs/member", "JSON-LD schemas should validate typed graph members");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.properties?.["@type"]?.const === "schema:CreativeWork")), "JSON-LD schemas should describe source members");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.properties?.["@type"]?.const === "lfn:Relation")), "JSON-LD schemas should describe relation members");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.properties?.["@type"]?.contains?.const === "lfn:Concept")), "JSON-LD schemas should describe concept members");
assert(jsonLdSchema.$defs.member.oneOf.filter((variant) => variant.allOf?.some((part) => part.properties?.["@type"]?.const === "lfn:Relation" || part.properties?.["@type"]?.contains?.const === "lfn:Concept")).every((variant) => variant.allOf?.some((part) => part.required?.includes("lfn:sources"))), "JSON-LD concept and relation members should preserve explicit provenance references");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.required?.includes("lfn:addedAt"))), "JSON-LD source members should preserve creation chronology");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.required?.includes("lfn:createdAt") && part.required?.includes("lfn:updatedAt"))), "JSON-LD concept members should preserve update chronology");
assert.equal(jsonLdSchema.properties.learningExampleCount.maximum, 500, "JSON-LD roots should bound reusable learning memory");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.properties?.["@type"]?.const === "lfn:LearningExample")), "JSON-LD schemas should describe reusable learning members");
assert(fs.readFileSync(new URL("../jsonld-projection.js", import.meta.url), "utf8").includes('"sourceConcept": { "@id": "lfn:sourceConcept", "@type": "@id" }'), "JSON-LD context should declare learning endpoint references");
assert(jsonLdSchema.$defs.member.oneOf.some((variant) => variant.allOf?.some((part) => part.properties?.["lfn:sourceLabel"] && part.properties?.["lfn:targetLabel"])), "JSON-LD learning relations should preserve endpoint labels");
const learningMember = jsonLdSchema.$defs.member.oneOf.find((variant) => variant.allOf?.some((part) => part.properties?.["@type"]?.const === "lfn:LearningExample"));
assert(learningMember?.allOf?.some((part) => part.oneOf?.some((branch) => branch.properties?.["lfn:kind"]?.const === "concept" && branch.required?.includes("lfn:concept"))), "JSON-LD learning concepts should require concept references");
assert(learningMember?.allOf?.some((part) => part.oneOf?.some((branch) => branch.properties?.["lfn:kind"]?.const === "relation" && branch.required?.includes("lfn:sourceLabel") && branch.required?.includes("lfn:targetLabel"))), "JSON-LD learning relations should require endpoint references and labels");
assert.equal(jsonLdSchema.$defs.memberBase.properties["@id"].maxLength, 2000, "JSON-LD member identifiers should allow bounded escaped graph IDs");
assert.equal(jsonLdSchema.$defs.sourceRef.items.maxLength, 2000, "JSON-LD provenance references should match bounded escaped graph IDs");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("MAX_GRAPH_VERSION") && fs.readFileSync(new URL("../app.js", import.meta.url), "utf8").includes("advanceGraphVersion"), "graph mutations should guard safe-integer revision overflow");
assert(graphCore.includes("existing.lastReviewedAt = newestTimestamp(existing.lastReviewedAt, node.lastReviewedAt)") && graphCore.includes("existing.lastReviewedAt = newestTimestamp(existing.lastReviewedAt, edge.lastReviewedAt)") && graphCore.includes("existing.lastReviewedAt = newestTimestamp(existing.lastReviewedAt, nextEdge.lastReviewedAt)"), "duplicate graph items and merged relations should preserve the newest review timestamps");
assert(graphCore.includes("invalidatedNodeIds") && graphCore.includes("invalidatedEdgeIds") && graphCore.includes("lastReviewedAt: null"), "source mutations should invalidate review dates for affected graph items");
assert(graphCore.includes("setRemappedLearning") && graphCore.includes("preferLearningExample(existing, example)"), "concept merges should preserve the newest review timestamp for collapsed learning examples");
assert(graphCore.includes("existing.updatedAt = newestTimestamp(existing.updatedAt, node.updatedAt)"), "duplicate concept normalization should preserve the newest update timestamp");
assert(graphCore.includes("preferLearningExample") && graphCore.includes("incomingTime >= existingTime"), "all learning-memory write paths should resolve duplicate decisions by review freshness");
assert.equal(graphSchema.properties.redacted.type, "boolean", "graph schema should preserve redaction markers");
assert.equal(graphSchema.properties.graphFingerprint.pattern, "^fnv64-[0-9a-f]{16}-[0-9]+$", "graph JSON exports should support deterministic integrity fingerprints");
assert.equal(graphSchema.$defs.node.properties.aliases.maxItems, 20, "graph schema should bound aliases");
assert(graphSchema.$defs.evidence.required.includes("sources"), "evidence provenance is part of the graph contract");
assert.equal(graphSchema.$defs.evidence.properties.text.maxLength, 12000, "graph schema should bound evidence text");
assert.equal(graphSchema.$defs.evidence.properties.sources.maxItems, 200, "graph schema should bound evidence provenance references");
assert.equal(graphSchema.$defs.evidence.properties.sources.items.maxLength, 200, "graph schema should bound evidence provenance identity length");
assert.equal(graphSchema.$defs.document.properties.id.maxLength, 200, "graph schema should bound document identity length");
assert.equal(graphSchema.$defs.node.properties.id.maxLength, 200, "graph schema should bound concept identity length");
assert.equal(graphSchema.$defs.edge.properties.id.maxLength, 200, "graph schema should bound relation identity length");
assert.equal(graphSchema.$defs.edge.properties.source.maxLength, 200, "graph schema should bound relation endpoints");
assert.equal(graphSchema.$defs.edge.properties.target.maxLength, 200, "graph schema should bound relation endpoints");
assert.equal(graphSchema.$defs.revision.properties.reason.maxLength, 200, "graph schema should bound revision reasons");
assert.equal(graphSchema.$defs.revision.properties.nodes.maximum, 5000, "graph schema should bound revision node counts");
assert.equal(graphSchema.$defs.revision.properties.edges.maximum, 10000, "graph schema should bound revision edge counts");
assert.equal(graphSchema.$defs.node.properties.aliases.items.maxLength, 120, "graph concept aliases should be bounded");
assert.equal(graphSchema.$defs.learningExample.properties.aliases.items.maxLength, 120, "learning aliases should be bounded");
assert.equal(graphSchema.$defs.node.properties.mentions.maximum, 1000000, "graph mention counts should be bounded");
assert.equal(graphSchema.$defs.node.properties.feedback.maximum, 1000000, "graph feedback counts should be bounded");
assert.equal(graphSchema.$defs.edge.properties.feedback.minimum, -1000000, "graph feedback counts should have a lower bound");
assert.equal(graphSchema.properties.updatedAt.maxLength, 128, "graph timestamps should be bounded");
assert.equal(graphSchema.$defs.document.properties.addedAt.maxLength, 128, "document timestamps should be bounded");
assert.equal(graphSchema.$defs.document.properties.uri.maxLength, 2048, "source URIs should be bounded");
assert.match(graphSchema.$defs.document.properties.uri.pattern, /https\?/i, "graph URI schema should allow web schemes");
assert.equal(graphSchema.$defs.revision.properties.timestamp.maxLength, 128, "revision timestamps should be bounded");
const feedbackExampleSchema = feedbackSchema.properties.examples.items;
assert.equal(feedbackExampleSchema.properties.id.maxLength, 200, "feedback identity fields should match graph identity bounds");
assert.deepEqual(feedbackExampleSchema.properties.status.enum, ["accepted", "rejected"], "feedback exports should contain reviewed decisions only");
assert.equal(feedbackExampleSchema.properties.sources.maxItems, 200, "feedback provenance references should be bounded");
assert.equal(feedbackExampleSchema.properties.sources.items.maxLength, 200, "feedback provenance identity length should be bounded");
assert.equal(feedbackExampleSchema.properties.evidence.maxItems, 8, "feedback evidence should be bounded");
assert.equal(requestSchema.properties.feedback.items.$ref, "#/$defs/feedbackHint", "remote feedback should use the bounded hint contract");
assert.equal(requestSchema.properties.document.properties.uri.maxLength, 2048, "remote source URIs should be bounded");
assert.equal(requestSchema.properties.document.properties.uri.pattern, graphSchema.$defs.document.properties.uri.pattern, "remote URI schema should match graph URI safety");
assert.equal(diffSchema.$defs.item.properties.uri.pattern, graphSchema.$defs.document.properties.uri.pattern, "diff URI schema should match graph URI safety");
assert.equal(requestSchema.$defs.feedbackHint.properties.id.maxLength, 200, "remote feedback hint IDs should be bounded");
assert.deepEqual(requestSchema.$defs.feedbackHint.properties.status.enum, ["accepted", "rejected"], "remote feedback hints should contain reviewed decisions only");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("mergeSourceIds"), "graph merges should use bounded provenance merging");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("value.examples.slice(-MAX_FEEDBACK_EXAMPLES)"), "learning normalization should retain the newest bounded corrections");
assert.equal(feedbackSchema.properties.format.const, "llm-field-notes/feedback@1");
assert.equal(backupSchema.properties.format.const, "llm-field-notes/backup@1");
assert.match(backupSchema.properties.graphFingerprint.pattern, /^\^fnv64-/);
assert(!backupSchema.required.includes("graphFingerprint"), "backup fingerprints should remain optional for legacy backup compatibility");
assert(app.includes("fingerprintBackup") && app.includes("fingerprint does not match its graph and history"), "backup imports should verify content identity before restore");
assert.equal(evaluationComparisonSchema.properties.format.const, "llm-field-notes/evaluation-comparison@1");
assert.equal(evaluationSchema.properties.feedback.properties.datasetFingerprint.pattern, "^fnv1a-[0-9a-f]{8}(?:[0-9a-f]{8})?$");
assert.equal(evaluationSchema.$defs.acceptedMetric.properties.evidenceCoverage.maximum, 1, "evaluation reports should expose bounded evidence coverage");
assert.equal(evaluationSchema.$defs.acceptedMetric.properties.reviewedPrecision.maximum, 1, "evaluation reports should expose bounded reviewed precision");
assert.equal(feedbackSchema.properties.datasetFingerprint.pattern, "^fnv1a-[0-9a-f]{8}(?:[0-9a-f]{8})?$");
assert(!feedbackSchema.required.includes("datasetFingerprint"), "feedback fingerprints should remain optional for legacy dataset compatibility");
assert(app.includes("matchesFeedbackFingerprint"), "feedback imports should accept verified legacy fingerprints during migration");
assert.equal(healthSchema.properties.format.const, "llm-field-notes/health@1");
assert(!healthSchema.required.includes("graphFingerprint") && healthSchema.properties.graphFingerprint.pattern.startsWith("^fnv64-"), "health reports should add a backward-compatible deterministic graph fingerprint");
assert.equal(healthSchema.properties.health.properties.reviewCandidates.maximum, 15000, "health schemas should bound actionable review candidates");
assert.equal(healthSchema.properties.health.properties.staleReviewCandidates.maximum, 15000, "health schemas should bound stale review candidates");
assert.equal(healthSchema.properties.health.properties.staleLearningExamples.maximum, 500, "health schemas should bound stale learning examples");
assert.equal(healthSchema.properties.health.properties.freshSourceReviewCoverage.maximum, 100, "health schemas should bound fresh source coverage");
assert.equal(healthSchema.properties.gate.properties.thresholds.properties.maxReviewCandidates.maximum, 15000, "health schemas should bound review-candidate gates");
assert.equal(healthSchema.properties.gate.properties.thresholds.properties.maxStaleReviewCandidates.maximum, 15000, "health schemas should bound stale-review gates");
assert.equal(healthSchema.properties.gate.properties.thresholds.properties.maxStaleLearningExamples.maximum, 500, "health schemas should bound stale-learning gates");
assert.equal(healthSchema.properties.gate.properties.thresholds.properties.maxUnsupportedNodes.maximum, 5000, "health schemas should bound unsupported-concept gates");
assert.equal(healthSchema.properties.gate.properties.thresholds.properties.maxUnsupportedEdges.maximum, 10000, "health schemas should bound unsupported-relation gates");
assert.equal(healthSchema.properties.gate.properties.thresholds.properties.minFreshSourceReview.maximum, 100, "health schemas should bound fresh source-review gates");
assert.equal(packageManifest.scripts.health, "node experiments/inspect-graph.mjs", "graph health diagnostics should have an automation shortcut");
assert.equal(packageManifest.scripts["project:jsonld"], "node experiments/project-jsonld.mjs", "JSON-LD projection should have an automation shortcut");
assert.equal(packageManifest.scripts["verify:jsonld"], "node experiments/verify-jsonld.mjs", "JSON-LD verification should have an automation shortcut");
assert(fs.existsSync(new URL("../experiments/project-jsonld.mjs", import.meta.url)), "JSON-LD projection CLI should remain deliverable");
assert(fs.existsSync(new URL("../experiments/verify-jsonld.mjs", import.meta.url)), "JSON-LD verification CLI should remain deliverable");
assert(fs.existsSync(new URL("../experiments/inspect-graph.mjs", import.meta.url)), "graph health CLI should remain deliverable");
assert(fs.readFileSync(new URL("../experiments/inspect-graph.mjs", import.meta.url), "utf8").includes("const health = inspectGraph(graph)") && fs.readFileSync(new URL("../experiments/inspect-graph.mjs", import.meta.url), "utf8").includes("gate: runGate(health"), "graph health CLI should reuse one diagnostic pass for its report and gate");
assert(fs.readFileSync(new URL("../experiments/inspect-graph.mjs", import.meta.url), "utf8").includes("matchesGraphFingerprint(graph, graph.graphFingerprint)"), "graph health CLI should verify fingerprinted graph inputs");
assert(fs.readFileSync(new URL("../experiments/diff-graphs.mjs", import.meta.url), "utf8").includes("matchesGraphFingerprint(value, value.graphFingerprint)"), "graph diff CLI should verify fingerprinted graph inputs");
assert(fs.readFileSync(new URL("../experiments/evaluate-feedback.mjs", import.meta.url), "utf8").includes("matchesGraphFingerprint(extractionValue, extractionValue.graphFingerprint)"), "evaluation CLI should verify fingerprinted graph inputs, including wrapped extraction payloads");
assert(fs.readFileSync(new URL("../experiments/inspect-graph.mjs", import.meta.url), "utf8").includes("health.ambiguousLabels"), "graph health ambiguity gates should include duplicate concept labels");
assert(fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("npm run health -- graph.json") && fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("--max-stale-review-candidates") && fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("--max-stale-learning-examples") && fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("--min-fresh-source-review") && fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("--max-unsupported-nodes"), "the main README should document graph health automation and stale-learning gates");
assert(fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("only stale reusable learning memory") && fs.readFileSync(new URL("../ARCHITECTURE.md", import.meta.url), "utf8").includes("explicit, undoable cleanup action"), "public documentation should explain stale-learning cleanup semantics");
assert(fs.readFileSync(new URL("../schema/README.md", import.meta.url), "utf8").includes("stale reusable-learning counts") && fs.readFileSync(new URL("../schema/README.md", import.meta.url), "utf8").includes("--max-stale-learning-examples"), "the schema guide should document stale-learning health diagnostics");
assert(fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("--max-stale-review-candidates") && fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("--max-stale-learning-examples") && fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("--min-fresh-source-review") && fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("--max-unsupported-nodes"), "the experiment guide should document stale-learning gates");
assert(fs.readFileSync(new URL("../experiments/compare-evaluations.mjs", import.meta.url), "utf8").includes("at least one reviewed example"), "evaluation promotion should reject empty reviewed benchmarks");
assert(fs.readFileSync(new URL("../experiments/compare-evaluations.mjs", import.meta.url), "utf8").includes("contradictory reviewed decisions"), "evaluation promotion should reject conflicted reviewed benchmarks");
assert(fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("evaluation-comparison.schema.json"), "the public project map should document the evaluation promotion contract");
assert(fs.readFileSync(new URL("../schema/README.md", import.meta.url), "utf8").includes("evaluation.schema.json") && fs.readFileSync(new URL("../schema/README.md", import.meta.url), "utf8").includes("evaluation-comparison.schema.json"), "the schema guide should document evaluation contracts");
assert(fs.readFileSync(new URL("../schema/README.md", import.meta.url), "utf8").includes("graphFingerprint"), "the schema guide should document backup integrity fingerprints");
assert.equal(diffSchema.properties.format.const, "llm-field-notes/diff@1");
assert.equal(diffSchema.properties.graphSchema.const, "llm-field-notes/graph@1");
assert.equal(diffSchema.$defs.collection.properties.changed.maxItems, 10000, "graph diffs should remain bounded");
assert(diffSchema.properties.learning && diffSchema.properties.integrity, "graph diffs should include learning and integrity changes");
assert(diffSchema.properties.redaction, "graph diffs should include redaction state changes");
assert.equal(requestSchema.properties.operation.const, "extract-graph");
assert.equal(backupSchema.properties.graph.$ref, "graph.schema.json", "backup schema should resolve graph schema locally");
assert(html.includes("Content-Security-Policy") && html.includes("sha256-efybT6wtRaWZshwoqZ3HWV1NybxKXj9GmB5ie+Pw5iM=") && server.includes("sha256-efybT6wtRaWZshwoqZ3HWV1NybxKXj9GmB5ie+Pw5iM="), "the strict CSP should narrowly authorize structured discovery metadata");
assert(!html.includes("fonts.googleapis.com") && !fs.readFileSync(new URL("../styles.css", import.meta.url), "utf8").includes("fonts.googleapis.com"), "the local-first app should not require third-party font requests");
assert(server.includes("style-src 'self'; font-src 'self'"), "server CSP should keep styles and fonts same-origin");
assert(robots.includes("User-agent: *") && robots.includes("Allow: /"), "static deployments should expose an intentional indexing policy");
assert(html.includes('<meta name="robots" content="index,follow" />'), "the public wiki should declare its indexing intent");
assert(html.includes('<link rel="canonical" href="./" />'), "the public wiki should declare a canonical entry point");
assert(html.includes('rel="alternate" type="application/atom+xml" href="feed.xml"'), "the public wiki should advertise its optional Atom feed");
assert(html.includes('<noscript class="noscript-map">') && html.includes("Tokens are the interface") && html.includes("Ship the boring parts"), "the learning map should remain crawlable and usable without JavaScript");
assert(app.includes('class="note-source"') && app.includes("./notes/"), "interactive learning notes should expose durable Markdown sources");
assert(server.includes("learningNoteAssets") && server.includes('extname(entry.name) === ".md"') && server.includes('".md": "text/markdown; charset=utf-8"'), "Markdown learning notes should be safely deliverable");
assert(server.includes('const fixedPublicAssets = FIXED_PUBLIC_ASSETS;') && publicAssets.includes("export const PUBLIC_ASSETS") && publicAssets.includes("export const OFFLINE_SHELL_ASSETS"), "static serving and readiness should share one public asset allowlist");
for (const noteFile of fs.readdirSync(notesDirectory).filter((file) => file.endsWith(".md"))) {
  assert(serviceWorker.includes(`"./notes/${noteFile}"`), `service worker shell is missing learning note: ${noteFile}`);
  if (noteFile !== "README.md") {
    const noteId = noteFile.slice(0, -3);
    assert(app.includes(`id: "${noteId}"`), `app learning catalog is missing note: ${noteFile}`);
    assert(notesIndex.includes(`(${noteFile})`), `notes index is missing note link: ${noteFile}`);
  }
}
assert(publicAssets.includes('"CONTRIBUTING.md"') && html.includes('href="CONTRIBUTING.md"'), "the public contribution link should target an allowlisted asset");
assert(publicAssets.includes('"ARCHITECTURE.md"') && fs.readFileSync(new URL("../ARCHITECTURE.md", import.meta.url), "utf8").includes("# LLM Field Notes architecture"), "the architecture guide should be public and served");
const changelog = fs.readFileSync(new URL("../CHANGELOG.md", import.meta.url), "utf8");
assert(publicAssets.includes('"CHANGELOG.md"') && changelog.includes("# Changelog") && changelog.includes("## [Unreleased]"), "the release changelog should be public and served with current unreleased work");
assert(html.includes('href="ARCHITECTURE.md"'), "the architecture guide should be discoverable from the public wiki");
assert(html.includes('href="CHANGELOG.md"'), "the release changelog should be discoverable from the public wiki");
assert(publicAssets.includes('"README.md"') && publicAssets.includes('"SECURITY.md"'), "public deployment guidance should be allowlisted");
assert(publicAssets.includes('"CODE_OF_CONDUCT.md"') && conduct.includes("Expected behavior") && fs.readFileSync(new URL("../CONTRIBUTING.md", import.meta.url), "utf8").includes("CODE_OF_CONDUCT.md"), "community participation guidance should be public and linked");
assert(publicAssets.includes('"experiments/README.md"') && fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("tiny-bpe.mjs") && fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("tiny-training.mjs") && fs.readFileSync(new URL("../experiments/README.md", import.meta.url), "utf8").includes("tiny-transformer.mjs"), "runnable experiment documentation should be deliverable");
for (const match of html.matchAll(/(?:href|src)="([^"]+)"/g)) {
  const reference = match[1];
  if (!reference || reference.startsWith("#") || reference.startsWith("http:") || reference.startsWith("https:") || reference.startsWith("data:")) continue;
  const asset = reference.split("#", 1)[0].split("?", 1)[0].replace(/^\.\/+/, "") || "index.html";
  const dynamicallyAllowlistedNote = asset.startsWith("notes/") && asset.endsWith(".md") && server.includes("learningNoteAssets");
  const dynamicallyAllowlistedFeed = asset === "feed.xml" && server.includes('requestPath === "/feed.xml"');
  assert(publicAssets.includes(`"${asset}"`) || dynamicallyAllowlistedNote || dynamicallyAllowlistedFeed, `public shell reference is not in the static allowlist: ${asset}`);
}
const shellDefinition = serviceWorker.match(/const APP_SHELL = \[([\s\S]*?)\];/)?.[1] || "";
for (const match of shellDefinition.matchAll(/"([^"]+)"/g)) {
  const asset = match[1].replace(/^\.\/+/, "") || "index.html";
  const dynamicallyAllowlistedNote = asset.startsWith("notes/") && asset.endsWith(".md") && server.includes("learningNoteAssets");
  assert(publicAssets.includes(`"${asset}"`) || dynamicallyAllowlistedNote, `service-worker asset is not in the static allowlist: ${asset}`);
}
assert(server.includes("permissions-policy") && server.includes("cross-origin-opener-policy"), "server should restrict browser capabilities and cross-origin isolation");
assert(server.includes("x-frame-options"), "server should provide legacy clickjacking protection");
assert(server.includes("EXTRACTOR_AUTH_TOKEN") && server.includes("METRICS_AUTH_TOKEN") && server.includes("timingSafeEqual") && server.includes("www-authenticate") && server.includes("authentication_failures_total"), "reference APIs should support observable constant-time bearer guards");
assert(server.includes("compactFeedbackHint") && security.includes("compacts reviewed feedback at its trust"), "reference extraction should strip untrusted feedback fields before provider calls");
assert(server.includes("safeDiagnosticCode") && server.includes("EXTRACTOR_FAILURE"), "provider diagnostic codes should be bounded before structured logging");
assert(server.includes("responsesByStatus") && server.includes("llm_field_notes_http_responses_total"), "metrics should expose privacy-safe HTTP status counters");
assert(fs.readFileSync(new URL("../SECURITY.md", import.meta.url), "utf8").includes("EXTRACTOR_AUTH_TOKEN"), "security guidance should document the optional extraction bearer guard");
assert(security.includes("Production launch checklist") && security.includes("Obsidian export/import review"), "security guidance should include an actionable production launch checklist");
assert(readme.includes("production launch checklist") && readme.includes("normalizeExtractionForDocument"), "the main README should link deployment guidance and describe the provenance-preserving normalization boundary");
assert(fs.readFileSync(new URL("../CONTRIBUTING.md", import.meta.url), "utf8").includes("normalizeExtractionForDocument"), "contributor guidance should distinguish generic and provenance-preserving extraction normalization");
assert(fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes('credentials: "same-origin"'), "browser extraction should preserve same-origin gateway sessions without exposing tokens");
assert(server.includes("function sendEmpty"), "server should apply security headers to empty error responses");
assert(server.includes('"x-robots-tag": "noindex, nofollow"'), "operational JSON and metrics responses should opt out of crawler indexing");
assert(server.includes("function sendPlainText") && server.includes("function sendNotModified") && server.includes('["GET", "HEAD"].includes(request.method)') && server.includes("request.method === \"HEAD\""), "HTTP endpoints should preserve correct MIME, conditional responses, and HEAD parity");
assert(server.includes('"cache-control": "no-store"') && server.includes('resolvedFilePath.endsWith("sw.js")'), "error and service-worker responses should use safe cache policies");
assert(server.includes('resolvedFilePath.endsWith("version.json")'), "release metadata should use a revalidating cache policy");
assert(server.includes("realpath") && server.includes("resolvedFilePath"), "static serving should reject symlink escapes");
assert(server.includes("MAX_STATIC_ASSET_BYTES") && server.includes("metadata.size"), "static serving and readiness should bound public asset sizes");
assert(server.includes("PUBLIC_ORIGIN") && server.includes("sitemap.xml") && server.includes("xmlEscape"), "production deployments should have an opt-in crawlable sitemap projection");
assert(publicOrigin.includes("export function normalizePublicOrigin") && server.includes("./scripts/public-origin.mjs") && fs.readFileSync(new URL("../scripts/build-pages.mjs", import.meta.url), "utf8").includes("./public-origin.mjs"), "Node and Pages deployments should share one public-origin policy");
assert(server.includes("feed.xml") && server.includes("application/atom+xml"), "production deployments should have an opt-in Atom feed projection");
assert(server.includes('learningNoteAssets.filter((asset) => asset !== "notes/README.md")'), "runtime crawler projections should match the Pages learning-note set");
assert(server.includes("renderOriginAwareIndex") && server.includes("social-card.svg") && server.includes("feed.xml"), "configured public origins should produce absolute sharing metadata");
assert(server.includes("deriveLearningNoteTitle") && server.includes("realpathSync") && server.includes("startsWith(`${resolvedRoot}/`)") && server.includes("readFileSync"), "Atom feed title extraction should enforce static-root containment");
assert(server.includes("createHash") && server.includes("if-none-match") && server.includes("matchesEtag") && server.includes("304"), "static assets should support HTTP-compliant conditional ETag responses");
assert(server.includes('"content-length": responseContent.byteLength'), "static responses should expose byte-accurate content lengths");
assert(server.includes('".txt": "text/plain; charset=utf-8"'), "plain-text static assets should use an explicit MIME type");
assert(server.includes('["ENOENT", "ELOOP", "ENOTDIR"]'), "static serving should distinguish missing assets from server failures");
assert(html.includes('id="share-wiki"'), "the public wiki should have a share action");
assert(html.includes('name="twitter:card" content="summary_large_image"'), "social preview metadata should request a large share card");
assert(html.includes('property="og:url" content="./"') && html.includes('property="og:image" content="social-card.svg"') && html.includes('property="og:image:type" content="image/svg+xml"') && html.includes('property="og:image:width" content="1200"') && html.includes('property="og:image:height" content="630"') && html.includes('name="twitter:image"') && html.includes('name="twitter:image:alt"'), "social previews should declare their URL and production-sized share-card metadata");
assert(fs.readFileSync(new URL("../social-card.svg", import.meta.url), "utf8").includes("Turn documents") && fs.readFileSync(new URL("../social-card.svg", import.meta.url), "utf8").includes("living map"), "the share card should carry a readable product promise");
const structuredDataMatch = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert(structuredDataMatch, "the public wiki should expose structured discovery metadata");
const structuredData = JSON.parse(structuredDataMatch[1]);
assert.equal(structuredData["@type"], "WebApplication");
assert.equal(structuredData.isAccessibleForFree, true);
assert(structuredData.featureList.includes("Human feedback and iterative representation improvement"), "structured metadata should describe the self-improvement loop");
assert(app.includes("function openNote") && app.includes("#note=") && app.includes("openNoteFromLocation"), "learning notes should support shareable deep links");
assert(app.includes('class="open-note" href="#note='), "learning notes should expose real permalink anchors");
assert(app.includes("data-copy-note") && app.includes("Note link copied."), "learning notes should expose direct copy-link actions");
assert(app.includes("const noteHash = location.hash.match") && app.includes("shareUrl.hash = noteHash || \"workbench\""), "sharing an open note should preserve its deep link");
assert(html.includes('aria-labelledby="dialog-title"') && html.includes('aria-describedby="dialog-question"'), "learning note dialogs should expose their accessible name and description");
assert(html.includes('id="progress-status"') && html.includes('aria-live="polite"'), "learning progress failures should have a visible status surface");
assert(app.includes("lastNoteTrigger") && app.includes('document.querySelector("#dialog-close").focus()') && app.includes("lastNoteTrigger.focus()"), "note dialogs should restore focus to their opener");
assert(app.includes("normalizeGraph"), "state normalization must remain wired");
assert(app.includes('document.querySelector("#try-sample")') && app.includes("loadSampleButton.click()") && app.includes("ingestButton.click()"), "the public onboarding path should offer a one-click local sample walkthrough");
assert(app.includes('location.hash === "#sample"') && app.includes('history.replaceState({}, "", "#workbench")'), "the installable app sample shortcut should launch the same onboarding walkthrough");
assert(app.includes("RELEASE_METADATA_TIMEOUT_MS") && app.includes("releaseController.signal"), "release metadata fetch should be bounded so startup cannot hang indefinitely");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes('normalizeId(inputSource.id) || `doc-${fingerprintText(sourceText)}`'), "extraction source IDs should be deterministic at the normalization boundary");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes('asText(node?.id).trim()'), "extraction concept IDs should repair explicit empty values");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("asDateTime(doc.addedAt"), "graph timestamps should be normalized at the graph boundary");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("normalizeSourceUri(doc.uri)"), "source URIs should be normalized at the graph boundary");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("SAFE_SOURCE_URI_SCHEMES"), "source URI schemes should be allowlisted");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("parsed.username") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("new RegExp(`^${scheme}://`"), "HTTP source URIs should reject ambiguous forms and embedded credentials");
assert(graphCore.includes("MAX_EXTRACTION_UNITS") && graphCore.includes("punctuatedUnits.length") && graphCore.includes("supplementalLineUnits") && graphCore.includes("splitPunctuated") && graphCore.includes("isMarkdownUnit"), "heuristic extraction should supplement prose with bounded Markdown units without merging separate list items");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("incomingSourceId") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("acceptedNodeIds"), "source replacement should retain provenance identity for accepted knowledge");
assert(app.includes("normalizeSourceUri(uriInput?.value") && app.includes("Use a valid review date."), "source metadata edits should validate dates and normalize URIs before persistence");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("DEFAULT_GRAPH_TIMESTAMP"), "malformed graph timestamp repairs should be deterministic");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("normalizeId(edge.id) ||"), "imported relation IDs should be repaired");
assert(app.includes("downloadFile"), "projection download must remain wired");
assert(app.includes('document.querySelector("#copy-markdown")') && app.includes("Markdown projection copied to the clipboard"), "the current Markdown projection should be directly shareable");
assert(app.includes("Learning ledger") && app.includes("accepted: ${accepted.length}") && app.includes("rejected: ${rejected.length}"), "Markdown projections should preserve the learning ledger");
assert(app.includes("`fingerprint: ${graphFingerprint}`") && app.includes("graphFingerprint = fingerprintBackup(graph)"), "Markdown projections should expose a deterministic graph fingerprint");
assert(app.includes("## Graph health") && app.includes("Active-item provenance coverage"), "Markdown projections should expose privacy-safe graph health diagnostics");
assert(app.includes("health = null") && app.includes("graphHealth = health || inspectGraph(graph)") && app.includes("buildMarkdown(graph, { maxEvidenceChars: MAX_MARKDOWN_PREVIEW_EVIDENCE_CHARS, graphFingerprint: projectionFingerprint, health })"), "the workbench should reuse one health snapshot when rendering the live Markdown preview");
assert(app.includes("graphFingerprint = fingerprintBackup(graph)") && app.includes("buildMarkdown(graph, { graphFingerprint })"), "vault projections should reuse one graph fingerprint across their Markdown and manifest outputs");
assert(app.includes("### Reusable memory") && app.includes("learningLines"), "Markdown projections should expose reusable learning memory");
assert(app.includes("Learning/review-ledger.md") && app.includes("type: learning-ledger"), "Obsidian projections should expose a navigable reusable-review ledger");
assert(app.includes("Revision history") && app.includes("graph.revisions.map((revision)"), "Markdown projections should preserve bounded revision history");
assert(app.includes("```mermaid") && app.includes("mermaidNodes") && app.includes(".slice(0, 300)"), "Markdown projections should include a bounded Mermaid graph view");
assert(app.includes("safeMarkdownLabel") && app.includes("quoteMarkdown"), "Markdown projections should escape link delimiters and multiline evidence");
assert(app.includes("safeMarkdownUri") && app.includes("https?:\\/\\/"), "Markdown projections should render only safe HTTP source URI links");
assert(app.includes("Source URI: ${safeMarkdownUri(doc.uri)}"), "Obsidian source notes should expose safe source URI links");
assert(app.includes("MAX_MARKDOWN_PREVIEW_EVIDENCE_CHARS") && app.includes("Evidence preview truncated"), "live Markdown previews should bound rendered evidence");
assert(app.includes("MAX_MARKDOWN_EXPORT_EVIDENCE_CHARS"), "full Markdown exports should bound evidence accumulation");
assert(fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("conflicts"), "evaluation reports should disclose contradictory feedback");
assert(fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("hasDetailedIdentity") && fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("forwardEndpointMatches") && fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("reverseEndpointMatches") && fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("example.sourceLabel"), "evaluation should validate portable relation labels and endpoint pairs even when relation IDs differ");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("export const relationSemanticKey") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("knownEdges = new Map(graph.edges.map((edge) => [relationSemanticKey"), "graph relation identity should use one shared semantic key");
assert(fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("node.status !== \"rejected\"") && fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("edge.status !== \"rejected\""), "evaluation accepted recall should exclude explicitly rejected candidates");
assert(fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("evidence.sources?.includes(sourceId)"), "evaluation evidence coverage should require source-anchored evidence");
assert(fs.readFileSync(new URL("../evaluation.js", import.meta.url), "utf8").includes("reviewedPrecision") && fs.readFileSync(new URL("../experiments/compare-evaluations.mjs", import.meta.url), "utf8").includes("reviewedPrecision"), "evaluation promotion should expose reviewed candidate precision");
assert(app.includes("MAX_RENDERED_GRAPH_NODES") && app.includes("MAX_RENDERED_GRAPH_EDGES") && app.includes("refine search to inspect more"), "large graphs should bound DOM rendering and disclose omitted matches");
assert(app.includes("manualNodes = graph.nodes") && app.includes("searchIndex.nodeText(node).includes(query)"), "manual relation selectors should honor graph search filters");
assert(app.includes('else selectSource(candidate.id)') && app.includes('graphSearchQuery = "";') && app.includes('document.querySelector("#graph-search").value = "";') && app.indexOf('document.querySelector(".mini-button[data-view=\'list\']").click();') < app.indexOf('if (candidate.kind === "node") selectGraphNode(candidate.id);'), "review-next should reveal and scroll candidates before selecting them");
assert(app.includes("zipStore"), "Obsidian vault export must remain wired");
assert(app.includes("buildLearningVaultFiles") && app.includes("Learning/${note.id}.md"), "Obsidian vaults should include the versioned learning notes");
assert(app.includes('name: "README.md"') && app.includes("Open [[_index]]") && app.includes("Source of truth"), "Obsidian vaults should include orientation and round-trip guidance");
assert(app.includes("vault-manifest.json") && app.includes("graphFingerprint: fingerprintBackup(graph)"), "Obsidian vaults should include a graph-bound manifest");
assert(html.includes('id="download-jsonld"') && html.includes('id="download-redacted-jsonld"') && app.includes("buildJsonLd(graph)") && jsonLdProjection.includes("export function buildJsonLd") && app.includes("application/ld+json"), "the workbench should offer full and redacted JSON-LD projections");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("Embedded graph JSON metadata does not match its vault manifest") && app.includes("vault.graphError"), "vault imports should verify embedded graph JSON metadata against its manifest before applying feedback");
assert(app.includes("LEARNING_NOTE_TIMEOUT_MS") && app.includes("request timed out"), "learning-note vault fetches should be bounded and report stalled notes");
assert(app.includes("node experiments/tiny-training.mjs"), "the interactive training note should point to the runnable training artifact");
assert(app.includes("archive exceeds the 50 MB safety limit") && app.includes("download-vault"), "Obsidian vault exports should enforce their import size limit");
assert(app.includes("estimatedArchiveBytes") && app.includes("addVaultFile") && app.includes("buildLearningVaultFiles({ estimatedArchiveBytes"), "vault projection should preflight cumulative archive size while generating files");
assert(app.includes("VAULT_TOO_LARGE") && app.includes("if (error?.code === \"VAULT_TOO_LARGE\") throw error"), "vault size failures should not be downgraded to missing-note warnings");
assert(app.includes("archiveLength = offset + centralDirectory.length + end.length"), "vault exports should check size before final byte concatenation");
assert(app.includes("nextOffset + nextCentralLength + 22 > maxBytes"), "vault exports should preflight size before retaining all archive parts");
assert(app.includes("estimatedArchiveBytes += 30 + nameBytes.length + contentBytes.length + 46 + nameBytes.length"), "vault exports should preflight encoded file sizes before ZIP allocation");
assert(app.includes("MAX_EXPORT_BYTES") && app.includes("This export exceeds the 50 MB safety limit"), "text projections should enforce an export size limit");
assert(app.includes("buildFeedbackDataset"), "feedback dataset export must remain wired");
assert(app.includes("dataset fingerprint does not match its examples"), "feedback imports must verify dataset identity before applying learning decisions");
assert(app.includes("aliases: node.aliases"), "feedback export should preserve concept aliases");
assert(app.includes("applyFeedbackDataset") && app.includes("Feedback dataset imported") && app.includes("contradictory decision") && app.includes("already up to date") && app.includes("revision limit. Export a backup before importing more feedback"), "feedback conflicts, idempotent imports, and revision limits should be surfaced accurately");
assert(!app.includes("asArray(imported.history).slice(-HISTORY_LIMIT"), "backup history should be bounded after malformed entries are filtered");
assert(app.includes("const restoredHistoryCount = graphStore.readHistory().length"), "backup restore status should report actually retained undo history");
assert(app.includes("unmatched or invalid example"), "feedback imports should surface skipped examples");
assert(app.includes('document.querySelector("#document-file").value = ""'), "successful imports should reset the file input");
assert(app.includes("MAX_ACTIVE_FEEDBACK_CONCEPTS") || fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("MAX_ACTIVE_FEEDBACK_CONCEPTS"), "adaptive extraction should bound active feedback hints");
assert(server.includes("/api/extract-graph"), "reference extraction endpoint must remain wired");
assert(dockerfile.includes("HEALTHCHECK") && dockerfile.includes("readyz") && dockerfile.includes("Number.isInteger(configured)"), "container health checks should mirror validated server port fallback behavior");
assert(dockerfile.includes("USER node"), "container should not run as root");
assert(dockerfile.includes('CMD ["node", "server.mjs"]'), "container should exec Node directly for reliable signal handling");
assert(/FROM node:20-alpine@sha256:[0-9a-f]{64}/.test(dockerfile), "container base image should be digest-pinned");
assert(dockerignore.includes(".env") && dockerignore.includes("tests") && dockerignore.includes("llm-field-notes-*.zip") && dockerignore.includes("*.pem") && dockerignore.includes("*.sqlite") && dockerignore.includes("backups"), "container context should exclude secrets, development tests, private keys, databases, and local exports");
assert(server.includes("process.env.HOST"), "server host should be configurable for containers");
assert(server.includes("/readyz") && server.includes("Static app shell is unavailable") && server.includes("beginDrain"), "server should distinguish process health from app readiness and expose one drain primitive");
assert(server.includes("createRequire") && server.includes("APP_VERSION") && server.includes("llm_field_notes_build_info"), "operational endpoints should expose the deployed application version");
assert(server.includes("server.isDraining") && server.includes("Server is draining"), "readiness should fail while the server drains");
assert(server.includes("REQUEST_TIMEOUT_MS") && server.includes("HEADERS_TIMEOUT_MS") && server.includes("keepAliveTimeout"), "HTTP transport timeouts should be explicit");
assert(server.includes("REQUEST_ABORTED") && server.includes('request.once("aborted"'), "request-body reads should stop when clients disconnect");
assert(server.includes("response.destroyed || response.writableEnded"), "responses should avoid writes after client disconnects");
assert(server.includes("SIGTERM") && server.includes("draining active requests"), "server should drain requests during shutdown");
assert(server.includes("EXTRACTOR_RATE_LIMIT"), "server rate limit should be configurable");
assert(server.includes("content-length") && server.includes("request.resume()"), "server should reject declared oversized request bodies early");
assert(server.includes("size > MAX_BODY_BYTES") && server.includes("statusCode: 413"), "server should reject chunked oversized request bodies while streaming");
assert(server.includes("drainRequest") && server.includes("drainError"), "oversized request drains should remain error-safe");
assert(server.includes("requestContentType !== \"application/json\""), "server should validate the exact JSON media type");
assert(server.includes("durationMs") && server.includes("route: \"extract-graph\""), "server should support structured extraction logs");
assert(server.includes("const safeLog") && server.includes("result?.catch?.(() => {})"), "logger failures should be isolated from request handling");
assert(server.includes("Number.isFinite(configuredRateLimit)"), "invalid rate limit configuration should fail safe");
assert(server.includes("configuredPort > 0 && configuredPort <= 65535") && server.includes("process.env.HOST.trim()"), "invalid host and port configuration should fail safe");
assert(server.includes('server.once("error"') && server.includes("failed to listen"), "server startup errors should be handled explicitly");
assert(server.includes("route: \"static\"") && server.includes("safeLog"), "unexpected static failures should use safe structured logging");
assert(server.includes("EXTRACTOR_TIMEOUT_MS") && server.includes("AbortController") && server.includes("504"), "provider extraction should be bounded and cancellable");
assert(server.includes('request.once("aborted"') && server.includes('response.once("close"'), "provider work should stop when clients disconnect");
assert(server.includes("!response.writableEnded"), "provider responses should guard disconnected sockets");
assert(server.includes("abortActiveExtractors"), "graceful shutdown should abort active provider work");
assert(server.includes("closeIdleConnections"), "graceful shutdown should close idle keep-alive connections");
assert(fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("MAX_RESPONSE_BYTES"), "remote extractor responses should be bounded before parsing");
assert(fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("TextEncoder"), "remote response limits should be measured in encoded bytes");
assert(server.includes('import { MAX_FEEDBACK_CHARS, MAX_RESPONSE_BYTES } from "./extractor-adapter.js"'), "server and browser feedback limits should share one adapter contract");
assert(fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("responseMediaType !== \"application/json\""), "remote extractor responses should enforce the exact JSON media type");
assert(server.includes("MAX_RESPONSE_BYTES") && server.includes("EXTRACTOR_RESPONSE_TOO_LARGE") && server.includes("Buffer.byteLength(JSON.stringify(responsePayload))"), "server extractor responses should use the shared output bound");
assert(server.includes("MAX_FEEDBACK_EXAMPLES") && fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("MAX_FEEDBACK_EXAMPLES"), "feedback example limits should share the graph contract");
assert(server.includes("normalizeExtractionForDocument") && fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("normalizeExtractionForDocument"), "browser and server extraction should preserve submitted document provenance metadata");
assert(app.includes("renderInspector"), "evidence inspector must remain wired");
assert(app.includes("mergeConcepts") && app.includes("data-merge-node"), "the workbench should expose undoable concept merging");
assert(app.includes('tabindex="0" role="group" aria-label="Inspect concept') && app.includes('tabindex="0" role="group" aria-label="Inspect relation') && app.includes('document.querySelectorAll(".relation-row")') && app.includes('selectedRow.scrollIntoView({ block: "nearest" })'), "graph list rows should be keyboard discoverable and review navigation should reveal selected relations");
assert(app.includes('aria-label="Confirm relation') && app.includes('aria-label="Dismiss relation'), "relation feedback controls should identify their relation context");
assert(app.includes('document.querySelector("#node-list").addEventListener("keydown"') && app.includes('document.querySelector("#relation-list").addEventListener("keydown"'), "graph list rows should support Enter and Space activation");
assert(app.includes("data-select-source"), "source inspection links must remain wired");
assert(app.includes("data-inspector-feedback") && app.includes("REVIEW DECISION"), "the inspector should expose direct feedback actions for the active-learning loop");
assert(app.includes("function persistFeedbackDecision") && app.includes('persistFeedbackDecision("node"') && app.includes('persistFeedbackDecision("edge"'), "all feedback surfaces should share one conflict-safe persistence path");
assert(app.includes("document-uri") && app.includes("inspector-source-uri"), "source URI entry and editing must remain wired");
assert(app.includes('document.querySelector("#document-uri").value = "";'), "loading a new sample or file should not retain stale source URI provenance");
assert(app.includes("previewLimit"), "source previews must remain bounded");
assert(app.includes("pendingFiles"), "batch ingestion state must remain wired");
assert(app.includes("MAX_IMPORT_BYTES") && app.includes("file.size"), "browser imports should reject oversized files before reading them");
assert(app.includes("MAX_GRAPH_DOCUMENT_CHARS") && app.includes("document-text"), "graph ingestion should expose the aggregate source-text bound");
assert(app.includes("MAX_BATCH_FILES") && app.includes("MAX_BATCH_CHARS"), "batch imports should bound file count and aggregate text size");
assert(app.includes("declaredFeedbackBytes") && app.includes("feedbackChars"), "feedback-note batches should enforce aggregate bounds before and during reads");
assert(app.includes("MAX_ZIP_BYTES"), "browser vault imports should reject oversized ZIPs before reading them");
assert(app.includes("renderWorkbenchUnsafe"), "workbench error boundary must remain wired");
assert(app.includes("data-edit-source"), "source metadata editing must remain wired");
assert(app.includes("conflicting label") && app.includes("That concept label already exists") && app.includes("item.aliases"), "label and alias collisions should be surfaced instead of creating ambiguous concepts");
assert(app.includes("inspector-source-quality") && app.includes("inspector-source-reviewed"), "source quality and review-date editing must remain wired");
assert(app.includes("data-remove-source"), "source removal must remain wired");
assert(app.includes("replaceSource") && app.includes("data-replace-source"), "source replacement must remain wired");
assert(app.includes("diffGraphs") && html.includes('id="download-diff"'), "revision diff export must remain wired");
assert(app.includes("revision-diff-preview") && app.includes("LAST DIFF"), "the workbench should show a bounded inline latest revision diff");
assert(app.includes("redactGraph") && html.includes('id="download-redacted"'), "privacy-preserving graph export must remain wired");
assert(app.includes("That graph's fingerprint does not match its contents") && app.includes("graphFingerprint: fingerprintBackup(graph)"), "graph JSON imports and exports should verify deterministic integrity fingerprints");
assert(app.includes('name: "graph.json", content: JSON.stringify({ ...graph, graphFingerprint }'), "Obsidian vault graph JSON should preserve its manifest integrity fingerprint");
assert(app.includes('name: "graph.jsonld", content: JSON.stringify(buildJsonLd(graph)'), "Obsidian vaults should include the JSON-LD projection");
assert(graphCore.includes("graph.learning.examples = graph.learning.examples.map(redactEvidence)") && graphCore.includes("Array.isArray(item.evidence)"), "redaction must scrub reusable-learning evidence as well as graph-item evidence");
assert(graphCore.includes("if (graph.redacted === true)") && graphCore.includes("documents = graph.documents.map((document) => ({ ...document, text: \"\", uri: null }))"), "redacted markers should enforce the privacy boundary during graph normalization");
assert(app.includes("HEALTH_FORMAT") && html.includes('id="download-health"') && app.includes("inspectGraph(graph)") && app.includes("graphFingerprint: fingerprintBackup(graph)"), "privacy-safe graph health export must remain wired and content-bound");
assert(html.includes('id="download-redacted-vault"') && app.includes("llm-field-notes-redacted-vault.zip"), "privacy-preserving Obsidian vault export must remain wired");
assert(app.includes("Redacted projection") && app.includes("redacted: ${graph.redacted === true}"), "redacted Markdown projections should disclose their privacy state");
assert(app.includes("health.redacted") && app.includes("redacted source content"), "graph health should retain redaction visibility");
assert(app.includes("buildCompactFeedbackDataset") && html.includes('id="download-compact-feedback"'), "compact feedback export must remain wired");
assert(app.includes("datasetFingerprint: fingerprintFeedbackExamples(examples)"), "compact feedback exports must recompute identity after removing source material");
assert(fs.readFileSync(new URL("../ARCHITECTURE.md", import.meta.url), "utf8").includes("explicit privacy levels"), "architecture should document projection privacy levels");
assert(html.includes('title="Includes evidence and source references"') && html.includes('title="Removes evidence and source references"'), "feedback export privacy boundaries should be visible before download");
assert(app.includes("This graph is redacted"), "redacted graph imports should disclose unavailable source content");
assert(fs.existsSync(new URL("../experiments/diff-graphs.mjs", import.meta.url)), "the graph diff CLI should remain deliverable");
assert(fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("Replacing an updated source file"), "source replacement should be documented for users");
assert(app.includes("commitManualGraph"), "manual graph editing must remain wired");
assert(app.includes("inspectGraph"), "graph health diagnostics must remain wired");
assert(app.includes("health.ambiguousLabels") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("ambiguousLabels"), "ambiguous concept labels should be visible in graph health");
assert(app.includes("MAX_SEARCH_TEXT_CHARS") && app.includes("MAX_SEARCH_EVIDENCE_CHARS"), "graph search indexing should bound evidence text per item");
assert(app.includes("health.ambiguousSourceIds") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("ambiguousSourceIds"), "ambiguous source IDs should be visible in graph health");
assert(app.includes("health.ambiguousSourceReferences") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("ambiguousSourceReferences"), "ambiguous provenance references should be visible in graph health");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("provenanceItems") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("supportedNodes.length + supportedEdges.length"), "provenance coverage should include active graph items, not only evidence records");
assert(app.includes("sourceReviewCoverage"), "graph health should expose source review coverage");
assert(app.includes("sourceQualitySummary"), "graph health should expose source quality distribution");
assert(!fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("Add a source-quality label"), "completed source metadata work should not remain in the roadmap");
assert(app.includes("reviewQueue") && fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("unresolved provenance"), "active-learning review queue should prioritize and explain provenance gaps");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("REVIEW_STALE_DAYS") && fs.readFileSync(new URL("../README.md", import.meta.url), "utf8").includes("stale"), "active-learning review queue should revisit stale human decisions");
assert(app.includes("Review next · ${candidate.reason}"), "review queue reasons should be visible when navigating to the next item");
assert(app.includes("data-review-action"), "review-next navigation must remain wired");
assert(app.includes("applyFeedback"), "feedback behavior must remain centralized in the graph core");
assert(app.includes("feedback} feedback"), "feedback state should be visible in the workbench");
assert(app.includes("node.lastReviewedAt") && app.includes("edge.lastReviewedAt") && app.includes("const reviewedAt = example.lastReviewedAt") && app.includes("last_reviewed: ${node.lastReviewedAt || \"\"}"), "human review timestamps should remain visible and exportable");
assert(html.includes('id="manual-edge-label"') && html.includes('aria-label="Relation label"'), "manual relation labels should have an accessible name");
assert([...html.matchAll(/<button\b[^>]*>/g)].every((match) => /\stype="button"/.test(match[0]) || /\stype="submit"/.test(match[0])), "static buttons should declare their form behavior explicitly");
assert(app.includes("node.status = \"accepted\"") && app.includes("edge.status = \"accepted\""), "human label edits should enter the reusable accepted-feedback loop");
assert(app.includes("syncLearningRelationLabels(graph).graph") && fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("syncLearningRelationLabels"), "concept corrections should keep relation learning endpoint labels synchronized");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("normalizeAliases(example.aliases)"), "feedback aliases should be bounded and deduplicated before normalization");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("const nodeById = new Map(graph.nodes.map"), "feedback imports should index graph items before applying examples");
assert(app.includes("buildExtractorFeedback") && !app.includes("buildFeedbackDataset(graph).examples"), "extraction requests should use compact reviewed feedback");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes('filter((node) => node.status === "accepted" || node.status === "rejected")'), "extractor feedback should exclude neutral inferred items");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("ambiguousConceptKeys"), "adaptive extraction should reject ambiguous feedback keys");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("const feedback = []"), "extractor feedback should balance concepts and relations under the shared cap");
assert(app.includes("applyObsidianFeedback"), "Obsidian feedback import must remain wired");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes('fields.type === "source"'), "source projection metadata should remain importable");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("manifestError") && app.includes("vault.manifest.graphFingerprint"), "vault imports should surface invalid or stale manifest identity");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("projectionMetadataError") && app.includes("feedback.graphFingerprint"), "individual Obsidian notes should surface invalid or stale projection identity");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("feedback.source === item.source") && fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("feedback.target === item.target") && fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("fields.source.trim()"), "relation projection imports should preserve and validate both endpoints");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("feedback.source === item.target") && fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("feedback.target === item.source"), "relation projection imports should preserve endpoint-order-insensitive identity");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("feedback.fingerprint !== source.fingerprint") && app.includes('`fingerprint: ${JSON.stringify(doc.fingerprint)}`'), "source projection imports should bind metadata edits to the source fingerprint");
assert(app.includes("staleVault || unverifiedVault") && app.includes("staleProjection || unverifiedProjection") && app.includes("window.confirm"), "stale or unverifiable Obsidian projections should require explicit confirmation before applying edits");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("duplicateField"), "Obsidian frontmatter should reject duplicate keys");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("Object.hasOwn(fields, \"status\")") && fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("hasReviewDate"), "Obsidian frontmatter should reject invalid mutation fields");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("MAX_FEEDBACK_NOTE_CHARS"), "Obsidian feedback notes should have an explicit parser bound");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("mismatched central and local filenames"), "ZIP imports should validate central and local filename agreement");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes("overlapping its central directory"), "ZIP imports should reject file data overlapping the central directory");
assert(fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8").includes('name.includes("\\\\")'), "ZIP imports should reject Windows-style unsafe paths");
assert(app.includes("parseObsidianVault"), "ZIP vault feedback import must remain wired");
assert(app.includes("download-redacted-markdown") && app.includes("redactGraph(graphStore.read())"), "the workbench should offer a privacy-safe Markdown projection");
assert(app.includes("looksLikeObsidianFeedback") && app.includes("Obsidian-shaped notes must be valid"), "malformed Obsidian-shaped notes should fail closed instead of becoming source documents");
const projectionAdapter = fs.readFileSync(new URL("../projection-adapter.js", import.meta.url), "utf8");
assert(projectionAdapter.includes("looksLikeObsidianFeedback") && projectionAdapter.includes("fields.last_reviewed.length > MAX_TIMESTAMP_CHARS") && projectionAdapter.includes("typeof fields.last_reviewed !== \"string\""), "all Obsidian note types should reject malformed review dates and expose shape detection");
assert(app.includes("Select an Obsidian vault ZIP by itself"), "mixed ZIP selections must be rejected");
assert(app.includes("invalidFeedbackFiles") && app.includes("no feedback was applied"), "malformed ZIP feedback notes should fail closed instead of being silently skipped");
assert(app.includes("paths.relations.get(edge)"), "relation projections must have collision-safe stable editable notes");
assert(app.includes("broken source reference"), "broken provenance must be visible in the health strip");
assert(app.includes("readRecovery"), "corrupt graph recovery must be wired");
assert(app.includes("data-recovery-action"), "recovery actions must be visible in the workbench");
assert(app.includes("readHistoryRecovery") && app.includes("history-download") && app.includes("history-dismiss"), "malformed undo history recovery must be visible and downloadable");
assert(app.includes('data-storage-action="backup"') && app.includes("exportBackupSnapshot"), "durable storage warnings should provide a direct validated backup action");
assert(app.includes("requestPersistentStorage"), "local graph durability request must remain wired");
assert(app.includes("navigator.share"), "share action should use the native share surface when available");
assert(app.includes("showProgressStorageError") && app.includes("progress may not persist") && app.includes("pathProgressKey") && app.includes("event.key === progressKey"), "learning progress should disclose storage failures and synchronize across tabs");
assert(app.includes("createRemoteExtractor"), "optional remote extraction must remain wired");
assert(app.includes("runRemoteExtraction"), "remote extraction cancellation must remain wired");
assert(app.includes("ingestInFlight") && app.includes("activeBuildController") && app.includes('setAttribute("aria-busy", "true")') && app.includes("documentFileInput.disabled = true") && app.includes("files.slice(fileIndex)"), "graph builds should lock competing UI actions and preserve canceled batch files");
assert(app.includes("endpointUrl.origin !== location.origin"), "browser extraction must respect same-origin CSP");
assert(app.includes("endpointUrl.username") && fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("embedded credentials"), "extractor endpoints should reject embedded credentials");
assert(app.indexOf("const endpoint = extractorEndpointInput.value.trim();") < app.indexOf("if (pendingFiles.length)"), "endpoint validation should not block feedback imports");
assert(app.includes("updatePrivacyNote"), "remote extraction data boundary must be disclosed dynamically");
assert(app.includes("Documents, optional source URI, and bounded reviewed feedback"), "remote privacy copy must include optional source URI metadata");
assert(html.includes("No document extraction call while the extractor endpoint is blank"), "privacy copy should distinguish static app requests from document extraction");
assert(app.includes("Saved with reduced undo history"), "degraded storage writes must be visible");
assert(app.includes("That feedback could not be saved"), "feedback persistence failures must be surfaced");
assert(app.includes("MAX_GRAPH_REVISIONS") && app.includes("graph.revisions = graph.revisions.slice(0, MAX_GRAPH_REVISIONS)"), "feedback revisions must remain bounded");
assert(app.includes("expectedVersion") && app.includes("changed in another tab"), "batch writes should detect cross-tab graph conflicts");
assert(app.includes("backup was not restored") && app.includes("import was not written"), "async imports should detect cross-tab graph conflicts");
assert(app.includes("manual change was not written") && app.includes("That feedback was not written") && app.includes("extraction was running"), "all graph mutations should surface cross-tab conflicts");
assert(app.includes("graphStore.clear(graphStoreOptions") && app.includes("graphStore.undo(graphStoreOptions"), "undo and clear should detect cross-tab graph conflicts");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes('lastWriteMode = "none"'), "no-op undo should not inherit stale write status");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes('lastWriteMode = "failed"'), "failed undo should report a failed write status");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("historyCapacity"), "history capacity should be sanitized before slicing");
assert(app.includes('window.addEventListener("storage"') && app.includes("Graph updated in another tab"), "the workbench should refresh after external graph changes");
assert(app.includes("sourceTitles") && app.includes("node.evidence.map"), "graph search should include source and evidence text");
assert(app.includes("health.reviewedItems"), "the workbench should expose accumulated feedback decisions");
assert(app.includes("health.acceptedItems") && app.includes("health.rejectedItems"), "the workbench should expose accepted and rejected learning outcomes");
assert(app.includes("health.staleReviewCandidates"), "the workbench should expose stale review pressure");
assert(app.includes("health.staleLearningExamples"), "the workbench should expose stale reusable learning pressure");
assert(app.includes("health.freshSourceReviewCoverage"), "the workbench should expose fresh source coverage");
assert(app.includes("learningExamples") && app.includes("reusable learning example"), "the workbench should expose reusable learning memory");
assert(app.includes("clearLearningMemory") && app.includes("clearStaleLearningMemory") && app.includes('data-learning-action="clear"') && app.includes('data-learning-action="clear-stale"') && app.includes("Forget reusable learning memory") && app.includes("Fresh learning memory will remain"), "the workbench should allow all or stale reusable learning memory to be cleared safely");
assert(app.includes("rememberLearningItem") && app.includes("graph.nodes[graph.nodes.length - 1]") && app.includes("graph.edges[graph.edges.length - 1]"), "manual and in-app edits should feed reusable learning memory");
assert(app.includes("createGraphSearchIndex") && app.includes("documentTitleMap"), "graph search should reuse a per-render document title index");
assert(app.includes("nodeTextCache") && app.includes("edgeTextCache"), "graph search should cache per-render searchable text");
const storageAdapter = fs.readFileSync(new URL("../storage-adapter.js", import.meta.url), "utf8");
assert(app.includes("getBrowserStorage") && storageAdapter.includes("createMemoryStorage"), "the workbench should survive unavailable browser storage");
assert(app.includes("Browser storage is unavailable"), "storage fallback limitations should be disclosed");
assert(app.includes("await browserStorage.ready") && app.includes("hasDurableStorage") && app.includes("pagehide") && storageAdapter.includes("flush()"), "the workbench should hydrate and flush durable storage across page lifecycle boundaries");
assert(app.includes("MAX_PROGRESS_JSON_CHARS") && app.includes("notes.some((note) => note.id === item)") && app.includes("item < path.length"), "learning progress should validate persisted IDs and indices");
assert(storageAdapter.includes("indexedDB") && storageAdapter.includes("BroadcastChannel"), "browser storage should support durable hydration and cross-tab synchronization");
assert(app.includes("storageDurabilityFailure") && app.includes("Durable storage unavailable"), "durability failures should be disclosed in the workbench");
assert(storageAdapter.includes("notifyStatus") && storageAdapter.includes("storageFailure"), "storage failures should be observable rather than silently downgraded");
assert(storageAdapter.includes("hydrationAbandoned") && storageAdapter.includes("closeHydrationDatabase"), "late IndexedDB hydration should close abandoned connections");
assert(fs.existsSync(new URL("../storage-adapter.js", import.meta.url)), "the storage adapter should remain a separately testable module");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("const valid = stored.filter(isGraphRecord)") && fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("trimHistory(valid)"), "backup history should filter malformed snapshots before applying its capacity");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("JSON.stringify(stored) !== JSON.stringify(normalized)"), "repairable persisted graphs should be preserved before normalization");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("HISTORY_RECOVERY_KEY") && fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("captureRaw(historyRecoveryKey"), "malformed persisted undo history should be preserved before filtering");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("expectedFingerprint") && app.includes("expectedFingerprint"), "graph mutations should use content fingerprints in addition to versions for optimistic concurrency");
assert(fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("serializeHistory(history)") && fs.readFileSync(new URL("../graph-store.js", import.meta.url), "utf8").includes("serializeHistory(trimHistory(history))"), "undo and clear should preflight persisted history size");
assert(app.includes("MAX_GRAPH_NODES") && app.includes("MAX_GRAPH_EDGES") && app.includes("MAX_GRAPH_DOCUMENTS"), "manual and extracted graph growth should respect explicit graph caps");
assert(app.includes("failureSummary") && app.includes("failures.slice(0, 3)"), "batch ingestion should surface bounded actionable failure details");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("conflictingSource"), "source-ID collisions should be repaired before graph merge");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("sameContent"), "import normalization should preserve conflicting source records");
assert(app.includes("const nodeById = new Map(graph.nodes.map") && app.includes("relatedByNode"), "large graph rendering and projection should reuse indexed lookups");
assert(fs.readFileSync(new URL("../graph-core.js", import.meta.url), "utf8").includes("knownNodeAliases"), "graph ingestion should index canonical labels and aliases");
assert(app.includes("function buildFeedbackDataset(graph)") && app.includes("const nodeById = new Map(graph.nodes.map((node) => [node.id, node]))"), "feedback export should index relation endpoint labels");
assert(app.includes('filter((node) => node.status === "accepted" || node.status === "rejected")'), "feedback exports should exclude neutral inferred items");
assert(app.includes("document.quality") && app.includes("document.lastReviewedAt"), "graph search should include source provenance metadata");
assert(app.includes("getVisibleNodes(graph, searchIndex)"), "graph layout and lists should share one search index");
assert(bugTemplate.includes("name: Bug report") && bugTemplate.includes("id: reproduce"), "bug intake should request reproduction steps");
assert(featureTemplate.includes("name: Feature request") && featureTemplate.includes("id: proposal"), "feature intake should request a concrete proposal");
assert(learningNoteTemplate.includes("name: Learning note") && learningNoteTemplate.includes("short_version") && learningNoteTemplate.includes("failure_modes") && learningNoteTemplate.includes("try_it"), "learning-note intake should preserve the executable curriculum contract");
assert(security.includes("EXTRACTOR_RATE_LIMIT") && security.includes("trusted reverse") && security.includes("proxy"), "server deployment security guidance should remain present");
assert(security.includes("extractor endpoint is configured") && security.includes("optional source URI") && security.includes("bounded reviewed feedback") && security.includes("/metrics"), "security guidance should describe remote data and metrics boundaries accurately");
assert(security.includes("redacted Obsidian vault"), "security guidance should describe the redacted vault privacy boundary");
assert(dockerignore.split(/\r?\n/).includes("dist"), "Docker builds should exclude the generated static Pages artifact");
assert(dockerignore.split(/\r?\n/).includes("experiments/*.mjs") && dockerignore.split(/\r?\n/).includes("scripts/build-pages.mjs") && dockerignore.split(/\r?\n/).includes("scripts/check-release.mjs") && !dockerignore.split(/\r?\n/).includes("scripts/public-assets.mjs"), "Docker builds should exclude development modules while retaining the runtime asset contract");
const workflow = fs.readFileSync(new URL("../.github/workflows/verify.yml", import.meta.url), "utf8");
const pagesWorkflow = fs.readFileSync(new URL("../.github/workflows/pages.yml", import.meta.url), "utf8");
assert(workflow.includes("uses: actions/checkout@") && pagesWorkflow.includes("uses: actions/deploy-pages@"), "deployment workflows should remain explicit and action-backed");
for (const workflowText of [workflow, pagesWorkflow]) {
  for (const match of workflowText.matchAll(/^\s*uses:\s*([^\s@]+)@([^\s#]+)/gm)) {
    assert(/^[0-9a-f]{40}$/i.test(match[2]), `GitHub Action reference should be pinned to a commit SHA: ${match[0]}`);
  }
}
assert(workflow.includes('"18.x", "20.x", "22.x"'), "CI should verify the supported Node runtime matrix");
assert(workflow.includes("Smoke test npm start") && workflow.includes("127.0.0.1:18001/metrics") && workflow.includes('test "$status" -eq 143'), "CI should exercise and terminate the standard Node start command");
assert(workflow.includes("docker build --tag llm-field-notes:ci ."), "CI should build the deployment container");
assert(workflow.includes("Smoke test container readiness") && workflow.includes("127.0.0.1:18000/readyz") && workflow.includes("State.Health.Status"), "CI should verify both readiness and Docker health status");
assert(workflow.includes("docker stop --time 5") && workflow.includes("State.ExitCode"), "CI should verify graceful container shutdown");
assert(pagesWorkflow.includes("npm test") && pagesWorkflow.includes("npm run build:pages") && pagesWorkflow.includes("actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa") && pagesWorkflow.includes("path: dist") && pagesWorkflow.includes("actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e"), "Pages deployment should verify and publish the generated bundle");
const pagesBuilder = fs.readFileSync(new URL("../scripts/build-pages.mjs", import.meta.url), "utf8");
assert(pagesBuilder.includes("PUBLIC_FILES") && pagesBuilder.includes("PUBLIC_ASSETS") && pagesBuilder.includes("buildStaticFeed") && pagesBuilder.includes("xmlEscape") && pagesBuilder.includes("await rm(output") && pagesBuilder.includes(".nojekyll"), "Pages publication should use a clean, explicit static allowlist and generated feed");
assert(!pagesBuilder.includes('"server.mjs"') && !pagesBuilder.includes('"Dockerfile"') && !pagesBuilder.includes('"tests/"'), "Pages publication should not expose server, container, or test files");
assert(pagesBuilder.includes("deriveNoteSummary") && pagesBuilder.includes("withoutFrontmatter") && pagesBuilder.includes("paragraphs[0] || title"), "Pages publication should derive non-empty clean feed summaries from Markdown notes");
assert(pagesBuilder.includes("lexicalCompare") && !pagesBuilder.includes("localeCompare"), "Pages feed ordering should be locale-independent");
assert(app.includes("const lexicalCompare") && !app.includes("mergeTargets = graph.nodes.filter((candidate) => candidate.id !== node.id).sort((left, right) => left.label.localeCompare"), "browser merge-target ordering should be locale-independent");
assert(pagesBuilder.includes("\\u0000-\\u0008") && server.includes("\\u0000-\\u0008"), "XML crawler projections should remove invalid control characters before escaping");
assert(server.includes("MAX_CRAWLER_RESPONSE_BYTES") && pagesBuilder.includes("Generated feed exceeds the 2 MB crawler response limit"), "crawler projections should bound generated response sizes in Node and Pages deployments");
assert.equal(packageManifest.scripts["build:pages"], "node scripts/build-pages.mjs", "Pages publication should have a package command");
assert.equal(packageManifest.scripts["serve:pages"], "npm run build:pages && python3 -m http.server 8000 --directory dist", "Pages publication should have a local preview command");
assert(fs.existsSync(new URL("../tests/pages-smoke.mjs", import.meta.url)), "Pages publication should have a static preview smoke test");
assert(dependabot.includes("package-ecosystem: github-actions") && dependabot.includes("package-ecosystem: npm") && dependabot.includes("interval: weekly"), "dependency updates should cover workflow actions and npm metadata");
assert(app.includes("revision-items"), "revision timeline must remain wired");
assert(app.includes("BACKUP_FORMAT") && app.includes("format: BACKUP_FORMAT"), "full backup format must remain wired through the shared contract");
assert(fs.readFileSync(new URL("../extractor-adapter.js", import.meta.url), "utf8").includes("schema: GRAPH_SCHEMA"), "remote extraction should use the shared graph schema contract");
assert(app.includes("replace the current workspace") && app.includes("Graph import canceled"), "destructive graph imports should require explicit confirmation");
console.log("site check ok");
