export const MAX_STATIC_ASSET_BYTES = 10 * 1024 * 1024;
export const MAX_LEARNING_NOTE_ASSETS = 1000;
export const MAX_PUBLIC_ASSET_BYTES = 100 * 1024 * 1024;

export const CORE_SHELL_ASSETS = [
  "index.html",
  "styles.css",
  "app.js",
  "curriculum.js",
  "graph-core.js",
  "graph-store.js",
  "extractor-adapter.js",
  "rebuild-adapter.js",
  "projection-adapter.js",
  "jsonld-projection.js",
  "storage-adapter.js",
  "backup-crypto.js",
  "evaluation.js",
  "manifest.webmanifest",
  "icon.svg",
  "icon-192.png",
  "icon-512.png",
  "social-card.svg",
  "social-card.png",
  "sw.js",
  "version.json"
];

export const FIXED_PUBLIC_ASSETS = [
  ...CORE_SHELL_ASSETS,
  "share.html",
  "share.css",
  "share.js",
  "share-projection.js",
  ".well-known/security.txt",
  "404.html",
  "robots.txt",
  "README.md",
  "ARCHITECTURE.md",
  "CHANGELOG.md",
  "llms.txt",
  "LICENSE",
  "SECURITY.md",
  "RUNBOOK.md",
  "PRODUCTION_STATUS.md",
  "CODE_OF_CONDUCT.md",
  "CONTRIBUTING.md",
  "ARTIFACTS.md",
  "ARTIFACT_SUBMISSION.md",
  "artifacts.html",
  "examples/sample-graph.json",
  "examples/sample-graph.canvas",
  "examples/sample-service-health.json",
  "examples/sample-share.json",
  "experiments/README.md",
  "experiments/bounded-file.mjs",
  "experiments/compare-evaluations.mjs",
  "experiments/diff-graphs.mjs",
  "experiments/evaluate-feedback.mjs",
  "experiments/graph-input.mjs",
  "experiments/inspect-graph.mjs",
  "experiments/learning-loop.mjs",
  "experiments/tiny-bpe.mjs",
  "experiments/tiny-attention.mjs",
  "experiments/tiny-training.mjs",
  "experiments/tiny-transformer.mjs",
  "experiments/project-jsonld.mjs",
  "experiments/verify-jsonld.mjs",
  "experiments/verify-graph.mjs",
  "experiments/verify-backup.mjs",
  "experiments/verify-diff.mjs",
  "schema/graph.schema.json",
  "schema/feedback.schema.json",
  "schema/share.schema.json",
  "schema/backup.schema.json",
  "schema/encrypted-backup.schema.json",
  "schema/diff.schema.json",
  "schema/evaluation-comparison.schema.json",
  "schema/health.schema.json",
  "schema/jsonld.schema.json",
  "schema/canvas.schema.json",
  "scripts/verify-canvas.mjs",
  "scripts/verify-service-health.mjs",
  "scripts/verify-share.mjs",
  "schema/service-health.schema.json",
  "schema/learning-loop.schema.json",
  "schema/vault-manifest.schema.json",
  "schema/extractor-request.schema.json",
  "schema/evaluation.schema.json"
];

export const LEARNING_NOTE_ASSETS = [
  "notes/README.md",
  "notes/tokens.md",
  "notes/embeddings.md",
  "notes/attention.md",
  "notes/training.md",
  "notes/transformers.md",
  "notes/scaling.md",
  "notes/inference.md",
  "notes/evaluation.md",
  "notes/rag.md",
  "notes/finetuning.md",
  "notes/agents.md",
  "notes/production.md",
  "notes/knowledge-graphs.md"
];

export const PUBLIC_ASSETS = [...FIXED_PUBLIC_ASSETS, ...LEARNING_NOTE_ASSETS];

export const PUBLIC_SITEMAP_ASSETS = [
  "artifacts.html",
  "sample-graph.html",
  "experiments/README.md"
];

export const GENERATED_PUBLIC_ASSETS = [
  "sample-graph.html"
];

export const OFFLINE_SHELL_ASSETS = [
  "./",
  ...CORE_SHELL_ASSETS.filter((asset) => asset !== "sw.js" && asset !== "version.json"),
  "LICENSE",
  "README.md",
  "ARCHITECTURE.md",
  "CHANGELOG.md",
  "llms.txt",
  "SECURITY.md",
  "RUNBOOK.md",
  "PRODUCTION_STATUS.md",
  "CONTRIBUTING.md",
  "ARTIFACTS.md",
  "ARTIFACT_SUBMISSION.md",
  "artifacts.html",
  "examples/sample-graph.json",
  "examples/sample-graph.canvas",
  "examples/sample-service-health.json",
  "examples/sample-share.json",
  "CODE_OF_CONDUCT.md",
  ".well-known/security.txt",
  "version.json",
  "experiments/README.md",
  "experiments/bounded-file.mjs",
  "experiments/compare-evaluations.mjs",
  "experiments/diff-graphs.mjs",
  "experiments/evaluate-feedback.mjs",
  "experiments/graph-input.mjs",
  "experiments/inspect-graph.mjs",
  "experiments/learning-loop.mjs",
  "experiments/tiny-bpe.mjs",
  "experiments/tiny-attention.mjs",
  "experiments/tiny-training.mjs",
  "experiments/tiny-transformer.mjs",
  "experiments/project-jsonld.mjs",
  "experiments/verify-jsonld.mjs",
  "experiments/verify-graph.mjs",
  "experiments/verify-backup.mjs",
  "experiments/verify-diff.mjs",
  "schema/graph.schema.json",
  "schema/feedback.schema.json",
  "schema/share.schema.json",
  "schema/backup.schema.json",
  "schema/encrypted-backup.schema.json",
  "schema/diff.schema.json",
  "schema/extractor-request.schema.json",
  "schema/evaluation.schema.json",
  "schema/evaluation-comparison.schema.json",
  "schema/health.schema.json",
  "schema/jsonld.schema.json",
  "schema/canvas.schema.json",
  "scripts/verify-canvas.mjs",
  "scripts/verify-service-health.mjs",
  "scripts/verify-share.mjs",
  "schema/service-health.schema.json",
  "schema/learning-loop.schema.json",
  "schema/vault-manifest.schema.json",
  ...LEARNING_NOTE_ASSETS
];
